### ISSUE TITLE
Could you include a map with the software.  I have tried my own maps, and they seem to be incorrect sizes.  Thank you!

### ISSUE THREAD

**Issue by jbalmer1** [uyke/survivotronkit#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AndyLee1024** [comment]
same here

**Comment by guxlar** [comment]
Hi, you can download and use the sample map of the Wiki. Check it here: https://github.com/uyke/survivotronkit/wiki/maps

Just right-click on the map and save it to your disk.

Hope it helps.

**Comment by jbalmer1** [comment]
Thank you! I will try it. :)
